baseurl: "https://finopsshow.com/"
# title: "The FinOps Show"
theme: "zen"
languageCode: "en-GB"       # Set your language code (only needed for none multilingual sites).

params:
  cookieConsent: true       # Show cookie consent form, default false.
  #contact: "info@example.org"
  copyright: "Copyright The FinOps Show"
  dateformat: ""            # Set the date format, default to "2 January, 2006"
  description: "The FinOps Show Podcast"           # Set site description, used in meta tags and JSON-LD
  favicon: ""               # Relative path to favicon in json feed, no leading slash.
  feedlinks: true           # Show feed links in the footer.
  footer: "A FinOps Show production."
  icon: "favicon.ico"       # Relative path to icon in json feed and JSON-LD, no leading slash.
  image: "logo.png"         # Relative path to site image in JSON-LD, no leading slash.
  imageMaxWidth: ""         # Max width for images added via figure shortcode.
  jquery: true              # Add jQuery
  languageDir: ""           # Set ltr or rtl, defaults to ltr.
  logo: true                # Turn off the logo.
  logoPath: logo.png        # Relative path to site logo, defaults to "images/logo.png", no leading slash.
  mainSections:             # The sections you want to have listed on the front page.
    - "episodes"            # Default to the section with most content if not set.
    - "host"                # Set to empty if no section should be listed.
  microUsername: ""         # Your micro.blog username.
  mobileMenu: true          # Turn on a mobile menu on small screens, default false.
  piwikSiteId:              # Matamo site id
  piwikTrackerUrl: ""       # Matamo url, schemaless and no slash on end (example.org/matamo).
  plausibleSiteID: ""       # Plausible site id/domain.
  plausibleTrackerURL: ""   # Plausible url, schemaless and no slash on end. Optional, defaults to "plausible.io/…"
  poweredby: false          # Show powered by hugo in footer
  privacyPolicyUrl: ""      # If set will add link to cookie consent form.

  realfavicongenerator:     # If full set of favicons, site manifest etc. exists, default false.
  relatedposts: true        # Show related posts under a "See also" section, default false.
  searchLimit: 20           # Max number of search hits, default 20.
  sidebar: true             # Show a sidebar to the right, default false.
  submitted: true           # Show author and date information for a post.
  themeColor:               # Hex color value, used in meta tags, default "#ffffff".

  podcast:
    title: "The FinOps Show"
    description: "“The FinOps Show” breaks down cost-savings incites from world-class industry leaders.  FinOps is an emerging practice that helps companies focus on computer infrastructure cost savings.   For years we have had a gap between company earnings, profits, and computer engineering costs, and our guests provide information that helps you bridge that black hole.  We bridge the     hole through culture and process changes backed by data and financial management."
    image:                  # * Feed image, place inside assets directory (iTunes).
    category:
      name:                 # * Feed category (iTunes).
      subcategories: []     # Feed sub category (iTunes).
    explicit: false    # Feed explicit settting, default to false (iTunes).
    author:                 # Feed author (iTunes).
    owner:
      name:                 # Feed owner name (iTunes).
      email:                # Feed owner e-mail (iTunes).
    lang:                   # Feed language, defaults to site language (iTunes).
    block: no           # Block the feed from iTunes, default to no (iTunes).
    complete: no        # Set the feed as complete, defaults to no (iTunes).
    type: episodic   # Podcast type, defaults to episodic (iTunes).
    newfeed:                # Are you moving? Set the new feed url here (iTunes).
    cdn:                    # CDN url, no slash on end (https://cdn.example.org).
    local: false            # Are the audio files local (true) or remote (false), default to true.
    preload: metadata # Set on the HTML5 audio tag, defaults to "metadata

menu:
  nav:
  - name: Episodes
    url: episodes/
    weight: 1
  - name: About 
    url: about/
    weight: 2
  - name: Our Host 
    url: host/
    weight: 3
  - name: RSS
    url: index.xml
    weight: 4
    #  - name: Tags
    #url: tags/
    #weight: 3
    #- name: Categories
    #url: categories/
    #weight: 4
deployment:
  targets:
    - name: "gcs"
      url:  "gs://finopsshow.com"
markup:
  goldmark:
    renderer:
      unsafe: true
