[[deployment.targets]]
# An arbitrary name for this target.
name = "gcs"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://finopstoday.com"

